Version id 2428 stable [ci skip]

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,148 +1,132 @@
-# ANTsR Build
 language: r
-sudo: required
-cache:
-  - timeout: 1000
-  - packages
-  - ccache
+cache: packages
 warnings_are_errors: true
-bioc_required: false
+use_bioc: true
+bioc_required: true
 cran: http://cran.rstudio.com
-
+dist: trusty
+addons:
+  apt:
+    packages:
+    - libcurl4-openssl-dev
+    - libxml2-dev
+    - libfftw3-dev
+    - libgsl0-dev
+    - libgsl0ldbl
 os:
-  - linux
-  - osx
-
+- linux
+- osx
+osx_image: xcode9
 r:
-  - oldrel
-  - release
-  - devel
-
+- 3.3
+- 3.4
+- 3.5
+- release
+- devel
 matrix:
   allow_failures:
-    - r: devel
-    - os: osx
-
-latex: false
-compiler: clang
-osx_image: xcode9
-
+  - r: devel
 env:
   global:
-  - R_BUILD_ARGS=" --no-build-vignettes --no-manual "
-  - R_CHECK_ARGS=" --timings --as-cran --no-manual --install-args=--build"
-  - R_CHECK_TIME="TRUE"
-  - R_CHECK_TESTS="TRUE"
-  - _R_CHECK_TIMINGS_="0"
-  - BOOTSTRAP_LATEX=1
+  - R_BUILD_ARGS="--no-manual"
+  - R_CHECK_ARGS="--as-cran --install-args=--build"
+  - RGL_USE_NULL=TRUE
+  - WARNINGS_ARE_ERRORS=1
+  - PROJECT_NAME=neuroconductor-devel-releases
   - DISPLAY=:99.0
-  - _R_CHECK_FORCE_SUGGESTS_="0"
-
+  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
 before_install:
-  - ulimit -n 2048
-  - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
-  - export PROJ_DIR=`basename ${TRAVIS_BUILD_DIR}`
-  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
-  - export rver=`r_version`;
-  - fname=travis_helpers.sh
-  - wget -O ${fname} http://bit.ly/travis_helpers
-  - cat ${fname}; source ${fname}; rm ${fname}
-  - start_xvfb ;
-  - v8_install ;
-  - cat DESCRIPTION
-  - export PACKAGE_NAME=`package_name`
-  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
-  # does all the clang exports
-  - x=`export_clang_cxx`; eval ${x}
-  - if [ "$TRAVIS_OS_NAME" = "osx" ];
-    then
-      no_open_mp ;
-    fi
-  - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
-  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
-  - clang_cxx
-  - hdf5_install ;
-  - export cmake_version="3.11"
-  - cmake --version
-  - x=`cmake_setup`; echo "${x}"; eval ${x};
-  - cmake --version
-  - ./cleanup
-  - Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type = 'source', repos=c(CRAN='https://cran.rstudio.com'))"
-  - Rscript -e "install.packages( c('magrittr','testthat','knitr','rmarkdown','covr','devtools', 'desc',  'remotes', 'colormap' ), repos=c(CRAN='https://cran.rstudio.com'))"
-  - Rscript -e 'install.packages("rsvd")'
-  - Rscript -e 'install.packages("magic")'
-  - Rscript -e 'install.packages("ggplot2")'
-  - Rscript -e 'install.packages("psych")'
-  - Rscript -e 'install.packages("randomForest")'
-  - cd ..
-  - git clone https://github.com/muschellij2/ghtravis.git
-  - R CMD INSTALL ghtravis
-  - cd ANTsR
-  - gh_binary_install  stnava/ITKR ANTsX/ANTsRCore
-  - export ants_user=ANTsX
-  - echo "Done Binary Installs"
-
-install:
-  - echo "skip this"
-
+- ulimit -n 2048
+- export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
+- export PROJ_DIR=`basename $PWD`
+- echo "travis_wait*\.log$" >> .Rbuildignore
+- fname=travis_helpers.sh
+- wget -O ${fname} http://bit.ly/travis_helpers
+- cat ${fname}; source ${fname}; rm ${fname}
+- cat DESCRIPTION
+- start_xvfb ;
+- v8_install ;
+- dcmtk_install ;
+- export rver=`r_version`; echo $rver ;
+- export PACKAGE_NAME=`package_name`
+- export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
+- remove_neuroc_packages
+- export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
+- x=`export_clang_cxx`; eval ${x}
+- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
+- echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
+- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
+- clang_cxx
+- export cmake_version="3.11"
+- cmake --version
+- x=`cmake_setup`; echo "${x}"; eval ${x};
+- cmake --version
+- export ants_user=neuroconductor-devel-releases
+- echo "Installing Missing Deps ITKR"
+- install_missing_remote_deps_all ${ants_user}/ITKR
+- gh_binary_install ${ants_user}/ITKR ;
+- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" || "${PACKAGE_NAME}"
+  == "ANTsR" ]]; then Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type =
+  'source', repo = 'http://cran.rstudio.com')" ; fi
+- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" ]]; then export
+  R_BUILD_ARGS="${R_BUILD_ARGS} --no-build-vignettes " ; export R_CHECK_ARGS="--no-vignettes
+  ${R_CHECK_ARGS}" ; fi
+- if [[ "${PACKAGE_NAME}" != "ITKR" ]]; then echo "Installing Missing Deps ANTsRCore"
+  ; install_missing_remote_deps_all ${ants_user}/ANTsRCore; gh_binary_install_passive
+  ${ants_user}/ANTsRCore ; fi
+- if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]]; then echo
+  "Installing Missing Deps ANTsR" ; install_missing_remote_deps_all ${ants_user}/ANTsR
+  ; gh_binary_install_passive ${ants_user}/ANTsR ; fi
+- if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; then export _R_CHECK_FORCE_SUGGESTS_=false
+  ; fi
+- cat DESCRIPTION
+- install_remotes_no_dep
+- cat DESCRIPTION
+- echo $PATH ;
+- install_deps_no_suggests
+- install_python_requirements ;
+- R CMD javareconf ;
+- travis_run_cache
 script:
-  - x=`export_clang_cxx`; eval ${x}
-  - travis_wait 100 R CMD build ${R_BUILD_ARGS} .
-  - rm -f travis_wait*.log
-  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
-  - ls
-  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
-  - cat /home/travis/build/ANTsX/ANTsR/ANTsR.Rcheck/00install.out
-  - rm -f travis_wait*.log
-  - if [[ $CHECK_RET -ne 0 ]];
-    then
-      echo "R CMD check failed";
-      check_fail;
-      dump_logs;
-      check_warnings ;
-      travis_terminate 1;
-    fi
-
-
-after_failure:
-  - dump_logs
-
+- x=`export_clang_cxx`; eval ${x}
+- travis_wait 100 R CMD build ${R_BUILD_ARGS} .
+- rm -f travis_wait*.log
+- PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
+- ls
+- travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
+- rm -f travis_wait*.log
+- if [[ $CHECK_RET -ne 0 ]]; then echo "R CMD check failed"; check_fail; dump_logs;
+  travis_terminate 1; fi
+- check_warnings
 after_success:
-  - dump_logs
-  - ls
-  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1);
-  - PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
-  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
-      PKG_FILE_NAME=$(ls -1t *.tgz | head -n  1);
-      PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
-    fi
-  - mv ${PKG_FILE_NAME} ${PKG_TARBALL_WITH_R} ;
-  - PKG_FILE_NAME=${PKG_TARBALL_WITH_R}
-
-notifications:
-  email:
-    recipients:
-    - muschellij2@gmail.com
-    - stnava@gmail.com
-    - arman.eshaghi@gmail.com
-    - jeff.duda@gmail.com
-    on_success: change
-    on_failure: always
-
-# so no overwrite of linux build
+- dump_logs
+after_failure:
+- dump_logs
 before_deploy:
-  - if [ "$TRAVIS_OS_NAME" = "osx" ];
-    then
-      rm -f *.tar.gz;
-    fi
-
+- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
+  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
+  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
+- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
+  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
+  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
+  ; fi
+- if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -f *.tar.gz; fi
 deploy:
   provider: releases
-  api_key:
-    secure: VevZHK5WDwd2mFSrF3+b2jTRzImb6juOgewcOvZ8LJ2S70khn64Kx4+JGUvk5miKWVbKnHIhPxOJY50muO9sT15ApP+HFZYpiVpx4l/hEypk9zmJD+f+ERuN7j8elCzUZqet3v77XD+pBcYMxFARew4gGDkG2LO5casij0YNiyQ=
-  file: ${PKG_FILE_NAME}
   skip_cleanup: true
+  file_glob: true
+  overwrite: true
+  file: "${PACKAGE_NAME}*.t*gz"
   on:
     tags: true
-    repo: ANTsX/${PROJ_DIR}
-    all_branches: true
+  api-key:
+    secure: hKzvi32XgSHsuT/5fmx5BAFQpB47VlDCuIeRQTaUXnBSo4WjxX6bL3hUeYNTw9yqZaEZLnzZi911I6l7LaggTDhzW9aEf5qE47yNIaHGPblB1rSqbsj3k8ZNdu6gZS/w/my+w8yq1FRjlhBEDuucvZP1xt0vF/0djLvI1cZphr7rkYvZV/l+S7uiyZqsxdsQbMkQqmD3IyoJyBQIzVtWZ3awuFBmLmxFPMAYsAunkzWCBmJuo7IoJbXt8p+EtN2BkL2YEArZ+BV8TfhZj1PO/HrBEItSQ3WnyPDZNOMapk4tAdmGBAqDvHZofJQtFJKq9VnsOw+zjUQeOSByHYErRrpQT00ugL8dz12wy4n3Xa2pz8hPjf+Xp5U+P+/XvLOFpYHLkqStPMpHWRQ+92i2Q09Ah8pM76vN0aHrPpB6F/Mut/Lj+BGaDtmaGRjU2XpaaXnjx9ikxS9C5KruENq/KhA9bJQeDyu8PBrakhbGBigZblFyZzZUMX8gBMVnEl8X2jcO8M7ZSxnZ336x/Be/zdNdA8Mz8U+Qs2E//GEJ5iD7UKsLp7zhXcrn3pRLDzJR29QS0nBoUcFwvbBKhMMhj34EBahuFYHgw309a9T4fo4rbwWFPBiCwNSK/bY6rLEsa6Jy3qDQq5doH0ZrytmqCZ0wzEHK0zQ4T82dkzxAHXc=
+after_deploy:
+- echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false";
+  else run_coverage=; fi;
+- if [[ "${PACKAGE_NAME}" != "ANTsR" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}"
+  != "ANTsRCore" && -z "${run_coverage}" ]]; then if [[ "${TRAVIS_R_VERSION_STRING}"
+  = "release" ]]; then Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)' ;
+  fi fi
+
+#neuroc.deps version (SHA): e2bc314
